"""env-guard CI/钩子配置生成器

支持生成：
- GitHub Actions 工作流配置
- GitLab CI 配置文件
- pre-commit hook 脚本
"""

from __future__ import annotations

import os
import stat
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from env_guard.models import ValidationStatus


@dataclass
class IntegrationConfig:
    """集成配置选项"""

    # 基础配置
    project_name: str = "my-project"
    python_version: str = "3.10"

    # GitHub Actions 配置
    github_workflow_name: str = "Security Scan"
    github_trigger_branches: list[str] = field(
        default_factory=lambda: ["main", "develop"]
    )
    github_include_history_scan: bool = True
    github_fail_on_secrets: bool = True

    # GitLab CI 配置
    gitlab_trigger_branches: list[str] = field(
        default_factory=lambda: ["main", "develop"]
    )
    gitlab_include_history_scan: bool = True
    gitlab_fail_on_secrets: bool = True

    # pre-commit hook 配置
    hook_type: str = "pre-commit"  # pre-commit, pre-push, commit-msg
    hook_stages: list[str] = field(default_factory=lambda: ["commit"])
    hook_fail_on_secrets: bool = True


class CIIntegrator:
    """CI/CD 集成配置生成器"""

    def __init__(self, config: Optional[IntegrationConfig] = None) -> None:
        self.config = config or IntegrationConfig()

    def generate_github_actions(self) -> str:
        """生成 GitHub Actions 工作流配置"""
        branches = ", ".join(
            f"'{b}'" for b in self.config.github_trigger_branches
        )

        history_job = ""
        if self.config.github_include_history_scan:
            history_job = """
  history-scan:
    name: Git History Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '{python_version}'

      - name: Install env-guard
        run: |
          pip install env-guard

      - name: Scan git history
        run: |
          env-guard scan --history --max-commits 100
        continue-on-error: {fail_on_error}

      - name: Upload security report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: env-guard-report.json
          retention-days: 30
""".format(
                python_version=self.config.python_version,
                fail_on_error="false"
                if not self.config.github_fail_on_secrets
                else "true",
            )

        return f"""# GitHub Actions Workflow - {self.config.github_workflow_name}
# Generated by env-guard

name: {self.config.github_workflow_name}

on:
  push:
    branches: [{branches}]
  pull_request:
    branches: [{branches}]
  schedule:
    # Run security scan daily at 2:00 AM
    - cron: '0 2 * * *'

permissions:
  contents: read

jobs:
  env-scan:
    name: Environment Files Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '{self.config.python_version}'

      - name: Install env-guard
        run: |
          pip install env-guard

      - name: Scan .env files
        run: |
          env-guard scan
        continue-on-error: {str(not self.config.github_fail_on_secrets).lower()}

      - name: Check .gitignore configuration
        run: |
          env-guard check-gitignore
        continue-on-error: {str(not self.config.github_fail_on_secrets).lower()}

{history_job}
  security-summary:
    name: Security Summary
    runs-on: ubuntu-latest
    needs: [env-scan]
    if: always()
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: security-*
          merge-multiple: true

      - name: Display summary
        run: |
          echo "## Security Scan Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Security scan completed. Check the artifacts for detailed reports." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Note:** Set `env-guard scan --fix` to automatically remediate issues." >> $GITHUB_STEP_SUMMARY
"""

    def generate_gitlab_ci(self) -> str:
        """生成 GitLab CI 配置文件"""
        branches = " | ".join(
            f'"{b}"' for b in self.config.gitlab_trigger_branches
        )

        history_job = ""
        if self.config.gitlab_include_history_scan:
            history_job = """
env-guard-history-scan:
  stage: security
  image: python:{python_version}-slim
  allow_failure: {allow_failure}
  script:
    - pip install env-guard
    - env-guard scan --history --max-commits 100
  artifacts:
    reports:
      dotenv: env-guard-vars.env
    paths:
      - env-guard-report.json
    expire_in: 1 week
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_COMMIT_BRANCH =~ /^({branches})$/'

""".format(
                python_version=self.config.python_version,
                allow_failure="yes"
                if not self.config.gitlab_fail_on_secrets
                else "no",
                branches=" | ".join(self.config.gitlab_trigger_branches),
            )

        return f"""# GitLab CI Configuration
# Generated by env-guard

stages:
  - security

variables:
  ENV_GUARD_VERSION: "latest"

env-guard-env-scan:
  stage: security
  image: python:{self.config.python_version}-slim
  allow_failure: {'yes' if not self.config.gitlab_fail_on_secrets else 'no'}
  before_script:
    - pip install env-guard
  script:
    - env-guard scan
    - env-guard check-gitignore
  artifacts:
    reports:
      dotenv: env-guard-vars.env
    paths:
      - env-guard-report.json
    expire_in: 1 week
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH =~ /^({branches})$/'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

{history_job}
security-gate:
  stage: security
  image: alpine:latest
  allow_failure: no
  needs: ["env-guard-env-scan"]
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^({branches})$/'
  script:
    - echo "All security checks passed!"
"""

    def generate_pre_commit_hook(self) -> str:
        """生成 pre-commit hook 脚本"""
        stages_str = ", ".join(f'"{s}"' for s in self.config.hook_stages)

        fail_flag = "1" if self.config.hook_fail_on_secrets else "0"

        return f"""#!/bin/bash
# pre-commit hook - Generated by env-guard
# 
# This hook scans for sensitive information before commits
# Install: Copy this file to .git/hooks/pre-commit and make it executable
# Or use: git config core.hooksPath hooks

set -euo pipefail

# Colors for output
RED='\\033[0;31m'
YELLOW='\\033[0;33m'
GREEN='\\033[0;32m'
NC='\\033[0m' # No Color

# Configuration
FAIL_ON_SECRETS={fail_flag}
SCAN_HISTORY=false

echo -e "{{YELLOW}}🔒 Running env-guard security scan...{{NC}}"

# Check if env-guard is installed
if ! command -v env-guard &> /dev/null; then
    echo -e "{{YELLOW}}⚠️  env-guard not found. Installing...{{NC}}"
    pip install env-guard > /dev/null 2>&1
fi

# Create temporary directory for reports
REPORT_FILE=$(mktemp)
trap 'rm -f "$REPORT_FILE"' EXIT

# Scan staged files for secrets
echo -e "{{YELLOW}}📁 Scanning staged files...{{NC}}"
if env-guard scan --staged --output "$REPORT_FILE" 2>&1; then
    # Check if secrets were found
    if grep -q "secrets" "$REPORT_FILE" 2>/dev/null || \
       grep -q "sensitive" "$REPORT_FILE" 2>/dev/null; then
        echo -e "{{RED}}❌ Sensitive information detected in staged files!{{NC}}"
        cat "$REPORT_FILE"
        if [ "$FAIL_ON_SECRETS" = "1" ]; then
            echo -e "{{RED}}🚫 Commit blocked due to security concerns.{{NC}}"
            exit 1
        fi
    fi
fi

# Check .gitignore configuration
echo -e "{{YELLOW}}📋 Checking .gitignore configuration...{{NC}}"
if ! env-guard check-gitignore 2>&1 | tee "$REPORT_FILE"; then
    if grep -q "missing" "$REPORT_FILE" 2>/dev/null; then
        echo -e "{{YELLOW}}⚠️  .gitignore may not properly exclude sensitive files.{{NC}}"
        if [ "$FAIL_ON_SECRETS" = "1" ]; then
            echo -e "{{RED}}🚫 Commit blocked - .gitignore configuration issue.{{NC}}"
            exit 1
        fi
    fi
fi

echo -e "{{GREEN}}✅ Security scan passed!{{NC}}"
exit 0
"""

    def generate_pre_commit_config(self) -> str:
        """生成 pre-commit-config.yaml 配置文件"""
        return f"""# pre-commit-config.yaml
# Generated by env-guard
# Install: pip install pre-commit && pre-commit install

repos:
  - repo: local
    hooks:
      - id: env-guard-scan
        name: env-guard security scan
        description: Scan for sensitive information in .env files
        entry: env-guard scan
        language: system
        stages: [{stages_str}]
        pass_filenames: false
        verbose: true

      - id: env-guard-gitignore
        name: env-guard gitignore check
        description: Verify .gitignore properly excludes sensitive files
        entry: env-guard check-gitignore
        language: system
        stages: [{stages_str}]
        pass_filenames: false
        verbose: true
"""

    def generate_dockerfile(self) -> str:
        """生成 Docker 配置用于 CI"""
        return f"""# Dockerfile for env-guard CI integration
# Generated by env-guard

FROM python:{self.config.python_version}-slim as builder

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir env-guard

# Runtime stage
FROM python:{self.config.python_version}-slim

WORKDIR /workspace

# Copy installed packages from builder
COPY --from=builder /usr/local/lib/python{self.config.python_version}/site-packages /usr/local/lib/python{self.config.python_version}/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

# Copy project files
COPY . .

# Default command
ENTRYPOINT ["env-guard"]
CMD ["--help"]
"""

    def save_github_actions(self, output_dir: Path) -> Path:
        """保存 GitHub Actions 配置到文件"""
        workflow_dir = output_dir / ".github" / "workflows"
        workflow_dir.mkdir(parents=True, exist_ok=True)
        file_path = workflow_dir / "security-scan.yml"
        file_path.write_text(self.generate_github_actions(), encoding="utf-8")
        return file_path

    def save_gitlab_ci(self, output_dir: Path) -> Path:
        """保存 GitLab CI 配置到文件"""
        file_path = output_dir / ".gitlab-ci.yml"
        file_path.write_text(self.generate_gitlab_ci(), encoding="utf-8")
        return file_path

    def save_pre_commit_hook(self, output_dir: Path) -> Path:
        """保存 pre-commit hook 脚本到文件"""
        hooks_dir = output_dir / "hooks"
        hooks_dir.mkdir(parents=True, exist_ok=True)
        file_path = hooks_dir / "pre-commit"
        file_path.write_text(self.generate_pre_commit_hook(), encoding="utf-8")
        # Make the hook executable
        file_path.chmod(file_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        return file_path

    def save_pre_commit_config(self, output_dir: Path) -> Path:
        """保存 pre-commit 配置文件"""
        file_path = output_dir / ".pre-commit-config.yaml"
        file_path.write_text(self.generate_pre_commit_config(), encoding="utf-8")
        return file_path

    def save_dockerfile(self, output_dir: Path) -> Path:
        """保存 Dockerfile"""
        file_path = output_dir / "Dockerfile.env-guard"
        file_path.write_text(self.generate_dockerfile(), encoding="utf-8")
        return file_path


def integrate_github_actions(
    project_path: Optional[str] = None,
    config: Optional[IntegrationConfig] = None,
) -> str:
    """快捷函数：生成并保存 GitHub Actions 配置"""
    integrator = CIIntegrator(config)
    output_dir = Path(project_path) if project_path else Path.cwd()
    file_path = integrator.save_github_actions(output_dir)
    return str(file_path)


def integrate_gitlab_ci(
    project_path: Optional[str] = None,
    config: Optional[IntegrationConfig] = None,
) -> str:
    """快捷函数：生成并保存 GitLab CI 配置"""
    integrator = CIIntegrator(config)
    output_dir = Path(project_path) if project_path else Path.cwd()
    file_path = integrator.save_gitlab_ci(output_dir)
    return str(file_path)


def integrate_pre_commit(
    project_path: Optional[str] = None,
    config: Optional[IntegrationConfig] = None,
    hook_type: str = "hook",
) -> str:
    """快捷函数：生成并保存 pre-commit 配置

    Args:
        project_path: 项目路径
        config: 集成配置
        hook_type: 'hook' 保存 shell 脚本, 'config' 保存 YAML 配置

    Returns:
        保存的文件路径
    """
    integrator = CIIntegrator(config)
    output_dir = Path(project_path) if project_path else Path.cwd()

    if hook_type == "config":
        file_path = integrator.save_pre_commit_config(output_dir)
    else:
        file_path = integrator.save_pre_commit_hook(output_dir)

    return str(file_path)


def integrate_all(
    project_path: Optional[str] = None,
    config: Optional[IntegrationConfig] = None,
) -> dict[str, str]:
    """快捷函数：生成并保存所有 CI/钩子配置

    Returns:
        包含所有生成文件路径的字典
    """
    integrator = CIIntegrator(config)
    output_dir = Path(project_path) if project_path else Path.cwd()

    results: dict[str, str] = {}

    results["github_actions"] = str(integrator.save_github_actions(output_dir))
    results["gitlab_ci"] = str(integrator.save_gitlab_ci(output_dir))
    results["pre_commit_hook"] = str(integrator.save_pre_commit_hook(output_dir))
    results["pre_commit_config"] = str(integrator.save_pre_commit_config(output_dir))
    results["dockerfile"] = str(integrator.save_dockerfile(output_dir))

    return results
